### ISSUE TITLE
Error when input is only a URL

### ISSUE THREAD

**Issue by cpenepent** [Mimino666/langdetect#12]
Context: grabbing text posts from Tumblr, one unique snowflake made a text post containing nothing except two Youtube URLs instead of making an actual video post or two, which my code would ignore entirely.  (Note: The following sample code does not contain either of the actual URLs I encountered.  Apologies in advance. #sorrynotsorry)

```python
from langdetect import detect
detect('https://www.youtube.com/watch?v=dQw4w9WgXcQ')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\langdetect\detector_factory.py", line 130, in detect
    return detector.detect()
  File "C:\Python27\lib\site-packages\langdetect\detector.py", line 135, in detect
    probabilities = self.get_probabilities()
  File "C:\Python27\lib\site-packages\langdetect\detector.py", line 142, in get_probabilities
    self._detect_block()
  File "C:\Python27\lib\site-packages\langdetect\detector.py", line 149, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.
```

I think I understand why this is happening -- detect is stripping out the URL correctly, leaving an empty string, which also causes detect() to raise an exception.  So what the heck do I do about this?  Does langdetect have any capacity to deal with this situation where cleaning results in an empty string, or do I just have to suck it up and hack together my own logic to detect URLs and replace them with something else* to deal with this dumb edge case?

*It looks like "xxx" would be a suitable replacement, which is detected by itself as language 'so', that way the previously mentioned post would be ignored by my code as not English.

**Comment by FelisPhasma** [comment]
I'm having this same error. It should be fixable with a simple try-except though...

**Comment by Mimino666** [comment]
The error is intended behavior, since it is impossible to detect language just based on URL.
The error message says it all: ``No features in text.``

**Comment by FelisPhasma** [comment]
@Mimino666 Alright, that's what I thought. As it turns out I am trying to exclude URLs from my analysis anyway. Thanks!

**Comment by anubhav0fnu** [comment]
@Mimino666 , @FelisPhasma Could you please suggest something on the issue?
https://github.com/Mimino666/langdetect/issues/44

**Comment by FelisPhasma** [comment]
@anubhav0fnu Hi, sorry for the late reply. I would do a preliminary parsing of the input to identify if it's a url, (Some regex should do the job).
