### ISSUE TITLE
Non Determinism

### ISSUE THREAD

**Issue by groceryheist** [Mimino666/langdetect#13]
calling detect on the following string returns 'fr' most of the time, but 'en' some of the time. 
python 3.4.

"Appuyez le projet de loi S-217 pour un minimum de 40% de femmes et d'hommes dans les CA\r\nSupport Bill S-217 to establish a minimum  of 40% of men and women on the boards of directors <p>FRA - Les canadiennes participent activement au milieu des affaires &agrave; titre de propri&eacute;taires d&rsquo;entreprises, d&rsquo;actionnaires, de dirigeantes, de gestionnaires et d&rsquo;employ&eacute;es et elles jouent un r&ocirc;le tout aussi important sur le march&eacute; en tant que consommatrices, elles devraient donc &ecirc;tre repr&eacute;sent&eacute;es de fa&ccedil;on &eacute;quilibr&eacute;e sur les conseils d&rsquo;administration. Appuyez le projet de loi S-217&nbsp; pour &eacute;tablir un minimum de 40% de femmes et d'hommes dans les CA des soci&eacute;t&eacute;s d'&Eacute;tat et des entreprises c&ocirc;t&eacute;es en bourse.</p>\r\n<p>ENG - Canadian women are actively involved in the corporate community as business owners, shareholders, executives, managers and employees, and they play an equally important role in the marketplace as consumers, they should have balanced representation on boards of directors. Support Bill S-217 to establish a minimum&nbsp; of 40% of men and women on the boards of directors of Crown corporations and publicly traded companies.</p>"

**Comment by keynmol** [comment]
Yeah, it's a bit ridiculous:

```
In [7]: detect_langs("Michael Jackson")
Out[7]: [en:0.5714284583773208, de:0.42857154155757843]

In [8]: detect_langs("Michael Jackson")
Out[8]: [de:0.6911409013095207, en:0.3088590986904793]

In [9]: detect_langs("Michael Jackson")
Out[9]: [en:0.5714279272461105, de:0.4285720098659035]

In [10]: detect_langs("Michael Jackson")
Out[10]: [de:0.7142858446749435, en:0.2857138775950282]

In [11]: detect_langs("Michael Jackson")
Out[11]: [de:0.5714288163404264, en:0.42857118177017683]
```

**Comment by Mimino666** [comment]
Non-determinism is part of a design from the original Google project. If you want to enforce determinism, see https://github.com/Mimino666/langdetect/issues/3.
