### ISSUE TITLE
Why there are probabilities returned as strings?

### ISSUE THREAD

**Issue by ziky90** [Mimino666/langdetect#14]
I am currently using `detect_langs()` an my text and it seems that it actually returns probabilities as strings instead of floats.
I would like to ask if there is some reason for this and if that wouldn't be better to return them as floats? I'm converting them always manually, but wouldn't be better to directly return floats?

**Comment by Mimino666** [comment]
Method `detect_langs()` returns list of Language objects. You can get the probability (as float) like this: 
```
>>> language = detect_langs(...)[0]
>>> language.prob
```
If it is not float, please provide me with your Python version and example code.

**Comment by ziky90** [comment]
Oh I can see it now. Thank you, everything works well like this.
