### ISSUE TITLE
decoding error in load profile

### ISSUE THREAD

**Issue by helmanofer** [Mimino666/langdetect#2]
When running langdetect.detect I get the following error:
    
    det_lang = langdetect.detect(lang)
      File "C:\Anaconda3\lib\site-packages\langdetect\detector_factory.py", line 122, in 
        init_factory()
      File "C:\Anaconda3\lib\site-packages\langdetect\detector_factory.py", line 119, in init_factory
        _factory.load_profile(PROFILES_DIRECTORY)
      File "C:\Anaconda3\lib\site-packages\langdetect\detector_factory.py", line 56, in load_profile
        raise LangDetectException(ErrorCode.FormatError, 'Profile format error in "%s" %s' % (filename, err))
    langdetect.lang_detect_exception.LangDetectException: Profile format error in "C:\Anaconda3\lib\site-packages\langdetect\profiles\af" 'charmap' codec can't decode byte 0x81 in position 738: character maps to <undefined>

I am using Anaconda 3
What fixes it for me is 

in "detector_factory.py", line 47 add "encoding='utf8'"
f = open(filename, 'r', encoding='utf8')

perhaps you didn't use the encoding because it breaks your supported languages that I am not aware of.
Note that I tested it on English and traditional Chinese

**Comment by Mimino666** [comment]
Nice catch. Fixed and pushed it to version 1.0.2.
Run "pip install langdetect --upgrade" and try again.
