### ISSUE TITLE
Detecting Serbian language doesn't work

### ISSUE THREAD

**Issue by Adelija** [Mimino666/langdetect#27]
Hello,
When I try to detect sentence on serbain
_s1="Данас је петак и није сунчано"
print detect(s1)_
I got following error
_UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)_
Can you help me about this? Thank you
All the best,
Adela

**Comment by Mimino666** [comment]
See issue https://github.com/Mimino666/langdetect/issues/25
