### ISSUE TITLE
How to restrict the list of accepted languages

### ISSUE THREAD

**Issue by tantale** [Mimino666/langdetect#28]
How can I restrict the list of accepted languages to the following:

- bg: Bulgarian
- cs: Czech
- da: Danish
- de: German
- el: Greek
- en: English
- es: Spanish
- et: Estonian
- fi: Finnish
- fr: French
- ga: Irish
- hr: Croatian
- hu: Hungarian
- it: Italian
- lt: Lithuanian
- lv: Latvian
- mt: Maltese
- nl: Dutch
- pl: Polish
- pt: Portuguese
- ro: Romanian
- sk: Slovak
- sl: Slovenian
- sv: Swedish

Currently, the date "23 ноември 2010 година" is detected as "mk" (Macedonian) instead of "bg" (Bulgarian).

Could you help, please.

**Comment by DebVortex** [comment]
@Mimino666 could you give a hint here? I have a similar problem. I get wrong results and restricting the languages to search for might help out.

Here a short example what I talk about:
```
>>> from langdetect import detect
>>> text = "Do I need an umbrella?"  # obviously english
>>> detect(text)  # should obviously not return 'it'
'it'
```

I tried to use ``detect_langs`` instead, iterate over the results and use the one of my supported languages with the highest probability. But:

```
>>> from langdetect import detect_langs
>>> text = "Do I need an umbrella?"  # still obviously english
>>> detect_langs(text)  # still obviously not english
[it:0.9999967333207996]
```

I only get the result for 1 language. Having an english  sentence and getting "Italian" with a prob of 0.9999 seems odd.

**Comment by tantale** [comment]
@DebVortex Yes, I fixed that. But I can't remember how. I check that in a few days… Stay tuned.

**Comment by tantale** [comment]
First, I created my own list of profiles in a `profiles` directory. I needed to create new profiles for "ga" gaelic and "mt" maltese.

    $ ls profiles/
    bg.json da.json el.json es.json fi.json ga.json hu.json lt.json mt.json pl.json ro.json sl.json
    cs.json de.json en.json et.json fr.json hr.json it.json lv.json nl.json pt.json sk.json sv.json

I my python module, I defined a `dict` of most spoken language, according to a [Wikipedia table](https://en.wikipedia.org/wiki/Languages_of_the_European_Union#Knowledge):

    #: Most spoken languages
    #: `<https://en.wikipedia.org/wiki/Languages_of_the_European_Union#Knowledge>`_
    MOST_SPOKEN_LANGUAGES = {
        'en': .51,
        'de': .32,
        'fr': .26,
        'it': .16,
        'es': .15,
        'pl': .09,
        'ro': .05,
        'nl': .05,
        'hu': .03,
        'pt': .03,
        'el': .03,
        'sv': .03,
        'cs': .03,
        'bg': .02,
        'sk': .02,
        'da': .01,
        'fi': .01,
        'lt': .01,
        'sl': .01,
        'et': .01,
        'hr': .01,
        'ga': .01,
        'lv': .01,
        'mt': .01,
    }

That way, English it at top.

To access my profiles, I created my own detector factory:

    LOCAL_PROFILES_DIRECTORY = os.path.join(os.path.dirname(__file__), "profiles")

    _detector_factory = None


    def get_detector_factory():
        global _detector_factory
        if _detector_factory is None:
            _detector_factory = langdetect.DetectorFactory()
            _detector_factory.load_profile(LOCAL_PROFILES_DIRECTORY)
        return _detector_factory


    def detect_lang(text):
        u"""
        Try to detect the language of the text.

        >>> detect_lang(u"12 August 2016")
        u'et de en'

        >>> detect_lang(u"12. August 2016")
        u'et de en'

        >>> detect_lang(u"Questions écrites par les membres du Parlement européen")
        u'fr pt es en ro nl de it sv'

        >>> detect_lang(u"Αύξηση της ανεργίας στην Κύπρο")
        u'el'

        >>> detect_lang(u"Заседания от 18 до 21 май 2015 г.")
        u'bg'

        >>> detect_lang(u"2015. május 18–21-i ülések")
        u'hu es fr et cs sk sl'

        >>> detect_lang(u"2010. november 23.")  # 'hu' not detected
        u'da sl sv nl en'

        :type  text: str|unicode
        :param text: Text sample

        :rtype: str
        :return: whitespace-delimited Languages codes.
        """
        detector = get_detector_factory().create()

        detector.set_prior_map(MOST_SPOKEN_LANGUAGES)

        detector.PROB_THRESHOLD = .000001

        detector.seed = 0
        detector.append(text)
        try:
            languages = detector.get_probabilities()
        except langdetect.lang_detect_exception.LangDetectException:
            return ''
        else:
            return ' '.join(language.lang for language in languages)

**note:** I needed to get a list of languages, so my own function could return space-delimited list of languages codes.

**Comment by tantale** [comment]
Here are my profiles for "ga" gaelic and "mt" maltese. There were compiled from documents downloaded from the [EU Law and Publications](https://publications.europa.eu/en/web/about-us/who-we-are).

[ga_mt_profiles.zip](https://github.com/Mimino666/langdetect/files/1278675/ga_mt_profiles.zip)

**Comment by CharlesGaydon** [comment]
This seems quite complex and my solution would be to map detected neighbor language to the target language. for instance afrikaans to dutch, etc.
