### ISSUE TITLE
Check if text belongs to a specific language

### ISSUE THREAD

**Issue by chribsen** [Mimino666/langdetect#29]
**Problem:**
Langdetect doesn't have an efficient implementation for checking if text belongs to a specific language. 

**Proposed solution:**
Implement a simple `check_language` method that takes some text and the language as an argument. Returns a `bool` that indicate if the language matches.

**Comment by slarrain** [comment]
Seems pretty simple:
```python
def check_language(text, language):
    return detect(text) == language
```
So:

```python
In [1]: from langdetect import detect

In [2]: def check_language(text, language):
   ...:     return detect(text) == language

In [3]: text = "Esto es una prueba"

In [4]: check_language(text, 'en')
Out[4]: False

In [5]: check_language(text, 'es')
Out[5]: True
```

Do you think is necessary?

**Comment by chribsen** [comment]
@slarrain Thanks for you comment. It's not an issue any longer as I am not actively using the module at the moment.

Let me clarify: 
The problem was the speed, really. Looking at the implementation, it's apparent that it will do a brute force search over all languages until it finds a match. 
Ideally, this should not be necessary with `check_language()` as it should only compare it to the target language.

I will close this issue for now. I might be submitting a PR request to fix this in the future, though.
