### ISSUE TITLE
langdetect doesn't seem to play nicely with multiprocessing by default

### ISSUE THREAD

**Issue by robbymeals** [Mimino666/langdetect#30]
Just wanted to bring your attention to this stackoverflow discussion: 
http://stackoverflow.com/questions/43268201/typeerror-init-missing-1-required-positional-argument-message-using-multip/43269116#43269116

I am not sure of exactly how this is happening and if I have more time, I will try and reproduce on a publicly available dataset and put the code here for further diagnosis. But it might be worth add the fix I described there to the readme?

**Comment by robbymeals** [comment]
Just tested fix, working nicely! Thanks!

**Comment by Calvinnncy97** [comment]
I am still having the same issue, and adding `init_factory` into ProcessPoolExecutor init function does not seem to work. Does anybody else have other solutions?

```Traceback (most recent call last):
  File "/usr/lib/python3.11/concurrent/futures/process.py", line 414, in wait_result_broken_or_wakeup
    result_item = result_reader.recv()
                  ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 250, in recv
    return _ForkingPickler.loads(buf.getbuffer())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LangDetectException.__init__() missing 1 required positional argument: 'message'```

**Comment by Moreh-LeeJunhyeok** [comment]
same here @Calvinnncy97 any updates?
