### ISSUE TITLE
LangDetectException: No features in text.

### ISSUE THREAD

**Issue by anubhav0fnu** [Mimino666/langdetect#44]
I am using langdetect to find foreign languages in a field in my MongDB database. While implementing it, I get to know that langdetect is scared of EMPTY strings, floating NaNs & URLs. 
I removed all the above conditions. But again, I am not able to find where langdetect is stuck again?  The detection is running on the "Description" field. There were around 34k records in the feild, when I randomly try to stop the loop till 7000 iteration, it has detected 1k foreign text, but after it failed. Can anyone suggest a way to see the record where it is failing. So that I can inspect a reason?
Below is the code:
`onlyText= data[['_id','Title','Text','Description']].set_index('_id').T.to_dict('list')
print('original Len:',len(onlyText))`
# remove NaN.
`nanRemoved={}
for key,val in onlyText.items():
    if str(val[2]) != 'nan':
        nanRemoved[key]=val
print('Len. after removing floating NaNs:',len(nanRemoved))`       
# remove empty strings.      
`emptyStringRemoved={}
for key,val in nanRemoved.items():
    if len(val[2])>0:
        emptyStringRemoved[key]=val
print('Len. after removing EMPTY strings:',len(emptyStringRemoved))`
# remove only Urls
`import re
url_cleaned={}
stop=0
import urlmarker
for key,val in emptyStringRemoved.items():
       if re.findall(urlmarker.URL_REGEX, val[2]):
        if re.findall(r"/((([A-Za-z]{3,9}:(?:\/\/)?)(?:[\-;:&=\+\$,\w]+@)?[A-Za-z0-9\.\-]+|(?:www\.|[\-;:&=\+\$,\w]+@)[A-Za-z0-9\.\-]+)((?:\/[\+~%\/\.\w\-_]*)?\??(?:[\-\+=&;%@\.\w_]*)#?(?:[\.\!\/\\\w]*))?)/",val[2]):
        stop+=1
       else:
        url_cleaned[key]=val
print('No. urls found:',stop)
print('Len. after removing Articles containing with URLs',len(url_cleaned))`

# start the langauge detection of the articles fields
`from langdetect import DetectorFactory
DetectorFactory.seed = 0
from langdetect import detect
defaulted={}
for key,val in url_cleaned.items():
    if detect(val[2]) !='en':
        defaulted[key]=val
print('Len. of articles having Foreign Text:',len(defaulted))`

`---------------------------------------------------------------------------
LangDetectException                       Traceback (most recent call last)
<ipython-input-248-c8c970f9c704> in <module>()
     39 for key,val in url_cleaned.items():
     40 #     stop=+1
---> 41     if detect(val[2]) !='en':
     42         defaulted[key]=val
     43 #     if stop ==15000:

> Output of any of the regex:

/Applications/anaconda3/lib/python3.6/site-packages/langdetect/detector_factory.py in detect(text)
    128     detector = _factory.create()
    129     detector.append(text)
--> 130     return detector.detect()
    131 
    132 

/Applications/anaconda3/lib/python3.6/site-packages/langdetect/detector.py in detect(self)
    134         which has the highest probability.
    135         '''
--> 136         probabilities = self.get_probabilities()
    137         if probabilities:
    138             return probabilities[0].lang

/Applications/anaconda3/lib/python3.6/site-packages/langdetect/detector.py in get_probabilities(self)
    141     def get_probabilities(self):
    142         if self.langprob is None:
--> 143             self._detect_block()
    144         return self._sort_probability(self.langprob)
    145 

/Applications/anaconda3/lib/python3.6/site-packages/langdetect/detector.py in _detect_block(self)
    148         ngrams = self._extract_ngrams()
    149         if not ngrams:
--> 150             raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
    151 
    152         self.langprob = [0.0] * len(self.langlist)

LangDetectException: No features in text.`

Please suggest.

**Comment by anubhav0fnu** [comment]
@mimino666 , @FelisPhasma What it is not able to understand? Any suggestions?

**Comment by Mimino666** [comment]
Error `No features in text` generally means, that there is no way to detect a language on the given input.

For example, when you pass in string (or a number): `222222`, what language is it? Can't tell, right? Similarly, when you pass just url: `https://www.mark.cn` or whatever.

To throw an exception at that point is the best way to handle such inputs. What you want to do is to catch the exception and handle the situation accordingly.

**Comment by anubhav0fnu** [comment]
@Mimino666 thank you so much, it didn't strike me. I did it 👍

**Comment by anubhav0fnu** [comment]
@Mimino666 
There are few texts which your library is not able to recognize. Please tell if on my end I can correct them in code. for ex:
1.detect("As of August 31, 2016,ccounted for 23 human cases of A(H7N9) virus infection, including four deaths; these infections were detected in Hong Kong (16 cases), Taiwan (four), Canada (two), and Malaysia (one).

Among 314 counties in China that reported at least one human A(H7N9) virus infection, 224 (71%) reported ≤2 infections. Most (83%) infections were reported in five eastern or southeastern coastal provinces. Whereas most infections in the first epidemic were identified during March–April 2013, the majority of infections identified in the subsequent three epidemics occurred during November–April of 2013–2014, 2014–2015, and 2015–2016 (Figure).")

2.detect(Home › Détente et loisirs › Santé › Epidémie de rougeole en Guinée : le Gouvernement prend des mesures… ›
Epidémie de rougeole en Guinée : le Gouvernement prend des mesures…
Santé
CONAKRY-Pour arrêter la progression de l’épidémie de rougeole qui frappe le pays, le gouvernement guinéen, à travers le ministère de la santé a lancé ce jeudi 6 avril 2017 une campagne de vaccination, à Conakry.
La cérémonie de lancement a été présidée par le ministre Abdourahmane Diallo. C’était en présence de certains partenaires de la Guinée dans le domaine sanitaires (OMS, UNICEF, MSF).
La campagne s’tendra du 7 au 15 avril 2017 dans les centres de santé et points de vaccination aménagés dans les quartiers et secteurs de la capitale. Elle touchera les enfants âgés de 6 mois à 10 ans.
Le Gouvernement avec l’appui de ses partenaires a mobilisé près de 3. 500.000 doses de vaccins contre la rougeole et a procédé à la vaccination des enfants de la Préfecture de N’zérékoré, qui était l’épicentre de cette épidémie, a indiqué le ministre de la santé.
Dr Abdourahmane Diallo a annoncé que des dispositions ont été également prises pour le traitement gratuit de tous les enfants malades de la rougeole dans les différentes formations sanitaires. Après N’zérékoré, Conakry est la deuxième localité la plus touchée par cette épidémie d’où, selon le ministre, la nécessité de la présente campagne de vaccination, l’unique moyen efficace pour arrêter la progression de l’épidémie.
Cette campagne de vaccination est totalement gratuite, a rappelé le ministre de la Santé, ajoutant qu’elle touchera un peu plus d’un million d’enfants âgé de 6 mois à 10 ans quel que soit leur statut vaccinal. Avant de clore son intervention, Dr Abourahmane Diallo a lancé un appel aux parents dans les différentes familles de faire vacciner leurs enfants.
« Je demande à toutes les familles, toutes les mères, les chefs de ménage des cinq communes de la ville de Conakry d’accepter que leurs enfants soient vaccinés contre la rougeole. Je lance un appel pressant aux vaccinateurs, aux mobilisateurs sociaux, aux superviseurs et à tous les acteurs impliqués dans la lutte contre la maladie, de faire preuve de responsabilité et d’engagement en vue de conférer à cette campagne un parfaite réussite », a lancé le ministre.
Les partenaires techniques et financiers s’engagent à accompagner le ministère de la Santé dans la riposte contre la présente épidémie de rougeole et le renforcement des services de vaccination dans le pays, a indiqué Dr Alfred Ki-Zerbo, représentant de l’organisation mondiale de la Santé en Guinée.
« Grâce à la vaccination anti rougeoleuse, les décès par rougeole dans le monde ont chuté de 79% entre 2000 et 2015, évitant 20.3 millions de décès », a renseigné M Ki-Zerbo.
La rougeole est une maladie très contagieuse due à un virus qui touche la couche infantile. Elle se transmet d’une personne à une autre par l’intermédiaire des gouttelettes émises par le malade. Elle est caractérisée par la fièvre, des éruptions cutanées, des conjonctivites, un rhume, une toux.  A ce jour 4254 cas de rougeole ont été notifiés dans 30 préfectures de la Guinée. La ville de Conakry en a enregistré 1590 soit 37% du total des cas.
 
)

**Comment by anubhav0fnu** [comment]
@Mimino666 
Your library is detecting the following text as 'Danish: da'. Could you please suggest why it is happening. Also, Sometimes, it is able to detect these text occurrences and sometimes not. What could be the reasoning behind that? Is this issue can be fixed?. When I query with the help of 'Regex' on the same column in MongoDB on which I have applied your langdetect, the query catches 51 occurrences of these texts, but the langdetect sometimes categories as 'Danish' & the count is just 2 & the other time just passes them to 'English' i.e fail to catch these occurrences.
print(detect("400 error"))
print(detect("403 error"))
print(detect("410 error"))
print(detect("404 error"))
print(detect("500 error"))
print(detect("503 error"))

**Comment by FelisPhasma** [comment]
Maybe identify if a text can be parsed instead of weather it can't. Some text should have features if it has at least 1 word, where a word is a string of letters and the first may be capitalized, ignoring punctuation on the ends but there shouldn't be punctuation in the middle of the string of letters....

**Comment by solub** [comment]
Hi, I'm facing the same problem mentioned by @anubhav0fnu but i don't know how to raise an exception accordingly. Would you mind sharing the snippet of code that can handle this situation ?

**Comment by anubhav0fnu** [comment]
Hello Louis D,

YOu can check the post now, I uploaded it.

Kindly suggest me if any further information is needed.

I look forward to hearing from you.

Thanks

Anubhav
Graduate Student
Computer science, Iowa State University
www.cs.iastate.edu/~anubhav
Contact No.: +1-515-735-8181 <(515)%20735-8181>

**Comment by solub** [comment]
@anubhav0fnu, Thank you very much !

**Comment by kanishk-verma-dotcom** [comment]
@anubhav0fnu 
Hi,
I tried using multiple except phrases to catch LangDetect Exception but to no avail
![image](https://user-images.githubusercontent.com/57866492/82884436-9fbbe700-9f3b-11ea-97ba-d04e5d1a71ba.png)

Still getting below error.
![image](https://user-images.githubusercontent.com/57866492/82884489-b104f380-9f3b-11ea-92df-aeb96c243ee3.png)

Any fix? 

Your help would be much appreciated. 

Thanks,
Kanishk

**Comment by anubhav0fnu** [comment]
> @anubhav0fnu
> Hi,
> I tried using multiple except phrases to catch LangDetect Exception but to no avail
> ![image](https://user-images.githubusercontent.com/57866492/82884436-9fbbe700-9f3b-11ea-97ba-d04e5d1a71ba.png)
> 
> Still getting below error.
> ![image](https://user-images.githubusercontent.com/57866492/82884489-b104f380-9f3b-11ea-92df-aeb96c243ee3.png)
> 
> Any fix?
> 
> Your help would be much appreciated.
> 
> Thanks,
> Kanishk

You've not handled correctly! the text you want to run lang detect on actually isn't a text at all! it's something else could be some gibberish UNICODE character! You need to put a seperate Try-catch for `lang = detect(str(desc[i]))' line and print the desc[i] and see what it is! 

The current error is due to the program execution has failed after the 3rd line! so the execution haven't reached existing try-catch in your code, you can comment that part- error will persist :) !

There is no issue in the library! the issue is in your code! write the correct code! Also, for such issues, you should be using debuggers and see where is the bug in your program! Learn to debug in python- Pycharm has a great visualization for debugging, you can use that as an IDE for both dev and debug purpose!  
Note: never paste an image instead of paste your `actual code`!
