### ISSUE TITLE
The langdetect wrongly classify text into danish language category.

### ISSUE THREAD

**Issue by anubhav0fnu** [Mimino666/langdetect#45]
@Mimino666 
Your library is detecting the following text as 'Danish: da'. Could you please suggest why it is happening. Also, Sometimes, it is able to detect these text kind of occurrences and sometimes not. What could be the reasoning behind that? Is this issue can be fixed?. When I query with the help of 'Regex' on the same column in MongoDB on which I have applied your langdetect, the query catches 51 occurrences of these texts, but the langdetect sometimes categories as 'Danish' & the count is just 2 & the other time just passes them to 'English' i.e fail to catch these occurrences. Also, Is it something to with non-determinism..?

```
print(detect("400 error"))
print(detect("403 error"))
print(detect("410 error"))
print(detect("404 error"))
print(detect("500 error"))
print(detect("503 error"))
```

**Comment by GitCMDR** [comment]
Yes. It has to do with being non-deterministic. This is expected behaviour.
