### ISSUE TITLE
How to add a new language

### ISSUE THREAD

**Issue by Garito** [Mimino666/langdetect#5]
Hi!
I would like to add catalan as available language
I understand that is a matter of add the n-grams for the particular case (something between spanish and french as a language so I don't expect any trouble) but I don really know the format or how to search or ask for (catalan people are so active on this kinds of issues so its easy they will help)

Could you, please, point me to the format or the name of the format?

Thanks!

**Comment by Mimino666** [comment]
Language profiles are usually generated from wikipedia articles.
There is a tool in official language-detection repository, that will help you with the task: https://code.google.com/p/language-detection/wiki/Tools

**Comment by Garito** [comment]
Hi!
Thanks for your help
I've downloaded the xml and generate the file, then I've putted on the profiles folder but it doesn't detect my new language

Did I miss something or there are additional steps to achive my goals?

Thanks!

**Comment by Mimino666** [comment]
Try to run the following commands:
```python
from langdetect import detector_factory 
detector_factory.init_factory()
print(detector_factory._factory.langlist)
```
You should see your newly added language in the list. Do you?

**Comment by Garito** [comment]
Yeah, it detects the new profile
But then it detects spanish instead of catalan

Catalan is a sort of mix between spanish and french. Could be the problem that the score for catalan is not good enought? how can i improve this score?

Thanks!

**Comment by Mimino666** [comment]
In that case, make sure you generated the profile from enough data.
Check the value of "n_words" in the profile file and compare it to the values in other profiles. The values should be approximately equal to ensure the good quality of detection.

**Comment by Garito** [comment]
I don't really know how to judge the data but I've collected some to make a picture:

af: 1541130, 1808182, 1328687
ar. 11749565, 13990834, 9440598
bg: 7994134, 9177756, 6462334
CA: 293152868, 351478644, 286024521 (the new one)
ES: 70286890, 82926999, 60413548 (the most picked by mistake but the nearest one)
FR: 66338594, 78580813, 56850284 (the second nearest)
de: 87197534, 99298261, 71857464
en: 260942223, 308553243, 224934017

What do you think about the numbers?

Why it doesn't detect catalan?

Thanks!!!

**Comment by Mimino666** [comment]
I will look into it. Please provide me with:
* detailed steps on how you generated the Catalan profile
* Catalan profile file
* list of texts on which it fails to detect Catalan language

Either upload the relevant files somewhere and provide me with the link, or fork the repository and upload the files.

**Comment by Garito** [comment]
I've downloaded this file: http://dumps.wikimedia.org/cawiki/20150308/cawiki-20150308-abstract.xml from http://dumps.wikimedia.org/cawiki/20150308/ as detailed https://code.google.com/p/language-detection/wiki/Tools (the link you give me)

The I've runned this
java -jar lib/langdetect.jar --genprofile-text -l [language code] [text file path]
from the same link you putted here

You could find the result here: https://github.com/Garito/langdetectfiles

I've putted this file at: my flask app/env/lib/python2.7/site-packages/langdetect/profiles/ca
If I activate this virtualenv and try to check if the ca file is include, it does (with the instructions you gave me)

And I'm using this wikipedia entry to make the tests: http://ca.wikipedia.org/wiki/Arbre

Please tell me if you need more info or I make some more tests

Thanks!

**Comment by Mimino666** [comment]
I have tried to regenerate Catalan language profile from the files you have provided and I've ended up with a different profile (see https://gist.github.com/Mimino666/cb7909648785113cdc37).

Now if you try to run langdetect with the profile I've generated, you will get the correct results.
Hope this will help.

**Comment by Garito** [comment]
Did you know what has my mistake generating them?
I'm going to try yours and check. I'll comment when done

Thanks a lot!

**Comment by Mimino666** [comment]
One thing comes to my mind. When you run command:
```
java -jar lib/langdetect.jar --genprofile -d [directory path] [language codes]
```
Make sure that [directory path] contains only the file *cawiki-20150308-abstract.xml* and nothing else.

**Comment by Garito** [comment]
Mmmm... I'll take note, thanks!
My first test was just fine
How possible is to include this language in your library? Did you plan to ship a new version to pypi soon?
I'm using docker to deploy so will be nice to have a new pypi version

Thanks a lot!

**Comment by Garito** [comment]
Awesome!
I've tryed sort sentences with es, ca and fr, the tree more near, and they work as a charm

Thanks! Yeah!

**Comment by Mimino666** [comment]
I've added Catalan language to main repository and increased to version 1.0.5.
You can upgrade the library.

**Comment by Garito** [comment]
My test are here: https://app.timefounder.com/projects/project-1
Sorry you need an account to see the detection feedback (feel free to ask one here: https://app.timefounder.com if you are interested in time founding)

Thanks a lot! I'm closing this issue if you don't mind

**Comment by kirthar** [comment]
Hi, thanks a lot for adding Catalan, I just need it today :)

Did you had this problem ? 

```
>>> from langdetect import detect_langs
>>> detect_langs("El director del Servei Català de Trànsit ha destacat que el retorn de les vacances ha sigut esglaonat")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/langdetect/detector_factory.py", line 132, in detect_langs
    return detector.get_probabilities()
  File "/Library/Python/2.7/site-packages/langdetect/detector.py", line 142, in get_probabilities
    self._detect_block()
  File "/Library/Python/2.7/site-packages/langdetect/detector.py", line 146, in _detect_block
    self.cleaning_text()
  File "/Library/Python/2.7/site-packages/langdetect/detector.py", line 121, in cleaning_text
    elif ch >= six.u('\u0300') and unicode_block(ch) != 'Latin Extended Additional':
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```

**Comment by Garito** [comment]
@kirthar change this:
detect_langs("El director del Servei Català de Trànsit ha destacat que el retorn de les vacances ha sigut esglaonat")
to:
detect_langs(u"El director del Servei Català de Trànsit ha destacat que el retorn de les vacances ha sigut esglaonat")

Since you have to use unicode and not a string

**Comment by kirthar** [comment]
@Garito great, thanks! :+1:

**Comment by kvi24** [comment]
Hi, I'm trying to add the Maori language to the library. I have downloaded the files as mentioned in the above posts. But when I tried the java -jar lib/langdetect.jar --genprofile -d [directory path] [language codes] in my command prompt, it's throwing an error. Could someone walk through the process for me, please? To run that code, which directory I should be in?

**Comment by andrebernardezbrana** [comment]
![image](https://user-images.githubusercontent.com/62541486/192466147-0bc0d732-0267-48b7-ba30-37992b271050.png)

**Comment by Walotex** [comment]
Im trying to create a MAYA (yua) language, I've already created the JSON but it is not detecting it for some reason. What can I do?
