### ISSUE TITLE
calling same text again and again gives random language

### ISSUE THREAD

**Issue by milanpatel** [Mimino666/langdetect#53]
I passes same text several times to detect api and it gives me en and sv randomly.
![langdetectbug](https://user-images.githubusercontent.com/852334/44102950-ee89787c-9fb8-11e8-839c-5f07e27cde5b.JPG)

detect('jason and his dad get new parts for jasons bike')
'en'
detect('jason and his dad get new parts for jasons bike')
'en'
detect('jason and his dad get new parts for jasons bike')
'sv'

**Comment by Mimino666** [comment]
See https://github.com/Mimino666/langdetect/issues/13
