### ISSUE TITLE
PyPI version of langdetect is out of date

### ISSUE THREAD

**Issue by Parker-Rule-Bose** [Mimino666/langdetect#55]
According to the [version release history](https://pypi.org/project/langdetect/#history) on PyPI, `langdetect` was last released in October 2016. There have been several fixes and changes to the codebase since then, including enhanced support for multiprocessing.

**Comment by iranzo** [comment]
Latest listed is for 2020 (1.0.8), I think that this can be closed @Parker-Rule-Bose
