### ISSUE TITLE
is bug?

### ISSUE THREAD

**Issue by wannaphongcom** [Mimino666/langdetect#7]
```python
>>> from langdetect import detect
>>> detect("Ein, zwei, drei, vier")
'de'
>>> detect("dog")
'pt'
>>> detect("ไง")
'th'
>>> detect("ไทย")
'th'
>>> detect("dog")
'pt'
>>> detect("dog")
'pt'
>>> detect("Ein, zwei, drei, vier")
'de'
>>> detect("cat")
'it'
```
dog is a pt lang. Is not an english language ? I require an  english language.
Thank you.

**Comment by Mimino666** [comment]
"dog" is too short text to detect a language. To use langdetect library confidently, use sentences with at least a couple of words in them.
