### ISSUE TITLE
Can you force the detection algorithm only to choose between a short list of languages?

### ISSUE THREAD

**Issue by joseberlines** [Mimino666/langdetect#84]
Imagine I know that the language I want to detect is en, fr, de, sp of it, how can I help the algorithm to force it to detect only those (and hence perhaps run faster)?

**Comment by hugovk** [comment]
Duplicate of #71? 

It has a solution/workaround:
* https://github.com/Mimino666/langdetect/issues/71#issuecomment-630238364

**Comment by joseberlines** [comment]
Thanks
